# Main settings of farmer
settings:
  # if you want to give farmer with economy leave it true
  buyFarmer: true
  # price of farmer necessary if buyFarmer is true
  farmerPrice: 1000
  # crates farmer automatically (If plugin supports)
  # also bypass money requirement
  autoCreateFarmer: false
  # default farmer user value
  # you can give farmer.user.<amount> perm to owner of farmer
  defaultMaxFarmerUser: 3
  # language from lang file
  lang: en
  # farmer ignore collecting if item dropped by player
  ignorePlayerDrop: false
  # Allowed worlds
  allowedWorlds:
    - ASkyBlock
    - Island
    - SuperiorWorld
    - bskyblock_world

# Tax rate
# If you set it 0 then it useless
# If you want to deposit tax amount to a player
# use depositUser and set true the deposit settings
tax:
  rate: 20
  deposit: false
  depositUser: Geyik

# Farmer levels
# Each level must has capacity and reqMoney
# First level must has capacity only
# Other settings are optional like reqPerm and tax
# If you want to make custom tax for a level then add tax: 1 etc.
# If you want to set a perm for level to purchase then add reqPerm: "my.perm"
levels:
  first:
    capacity: 1000
  second:
    capacity: 2000
    reqMoney: 5000
  third:
    capacity: 10000
    reqMoney: 8000
    reqPerm: "my.custom.perm"
    tax: 15